#893 Disable Jackson ObjectMapper FAIL_ON_UNKNOWN_PROPERTIES Deserialization Feature by default
jwtk/jjwt pull request #896
Opened 2024-01-18 09:31 UTC by amiriahmad72

Edit static `newObjectMapper` method of `JacksonSerializer`:
```
static ObjectMapper newObjectMapper() {
    return new ObjectMapper()
            .registerModule(MODULE)
            .configure(JsonParser.Feature.STRICT_DUPLICATE_DETECTION, true) // https://github.com/jwtk/jjwt/issues/877
            .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false); // https://github.com/jwtk/jjwt/issues/893
}
```
in order to disable Jackson `ObjectMapper` `FAIL_ON_UNKNOWN_PROPERTIES` Deserialization Feature by default .
Also add specific test with `json` which has unknown field and must seserialize to custom data type.

This fixs #893 

I close #894 PR and reopen this PR, because it has confilict with synchronous and same changes in #895 PR of @lhazlewood  

Thanks @lhazlewood

2024-01-25 12:44 UTC, amiriahmad72 commented
Hi @lhazlewood
Could you please check this PR?

2024-01-25 22:54 UTC, lhazlewood commented
@amiriahmad72 sorry about the delay, I should be able to review it properly today.

2024-01-26 05:34 UTC, lhazlewood requested changes

2024-01-26 05:34 UTC, lhazlewood commented on extensions/jackson/src/main/java/io/jsonwebtoken/jackson/io/JacksonSerializer.java
> +                .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false); // https://github.com/jwtk/jjwt/issues/893
@amiriahmad72 could you please update the JavaDoc for this method accordingly?

2024-01-27 00:00 UTC, lhazlewood approved these changes

2024-01-27 00:12 UTC, merged